data:
  batch_size: 256
  color_jitter_strength: 0.0
  crop_scale:
  - 0.3
  - 1.0
  crop_size: 224
  image_folder: /tachyum/local/datasets/coco2017/train2017
  num_workers: 4
  pin_mem: true
  root_path: /tachyum/local/datasets/coco2017
  use_color_distortion: false
  use_gaussian_blur: false
  use_horizontal_flip: false
logging:
  folder: /tachyum/local/mpechac/deployment/vitpose_vicreg/experiments_folder
  write_tag: jepa
mask:
  allow_overlap: false
  aspect_ratio:
  - 0.75
  - 1.5
  enc_mask_scale:
  - 0.85
  - 1.0
  min_keep: 10
  num_enc_masks: 1
  num_pred_masks: 4
  patch_size: 16
  pred_mask_scale:
  - 0.15
  - 0.2
meta:
  copy_data: false
  load_checkpoint: false
  model_name: vit_tiny
  pred_depth: 12
  pred_emb_dim: 384
  read_checkpoint: null
  use_bfloat16: false
optimization:
  ema:
  - 0.996
  - 1.0
  epochs: 400
  final_lr: 1.0e-07
  final_weight_decay: 0.001
  ipe_scale: 1.0
  lr: 0.0001
  start_lr: 0.00001
  warmup: 5
  weight_decay: 0.01

